import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import "./AgentPlatformConsole.css";

const platform = "http://127.0.0.1:8010";
type Site={id:number;domain:string;industry:string;country_code:string;language_code:string;workspace_project_id:number|null;is_legacy:boolean}; type Knowledge={id:number;title:string;source_type:string;status:string;content:string};
async function call<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(platform+path,{headers:{"Content-Type":"application/json"},...init});const b=await r.json();if(!r.ok)throw new Error(b.detail||"请求失败");return b as T;}
export function AgentPlatformConsole(){const nav=useNavigate(),{siteId}=useParams();const[sites,setSites]=useState<Site[]>([]),[docs,setDocs]=useState<Knowledge[]>([]),[notice,setNotice]=useState("加载站点中…"),[form,setForm]=useState({domain:"",industry:""}),[doc,setDoc]=useState({title:"",content:""});const active=sites.find(s=>s.id===Number(siteId));
 const refresh=async()=>{try{setSites(await call<Site[]>("/api/websites"));setNotice("每个网站使用独立关键词、标题、内容与知识库。")}catch(e){setNotice(e instanceof Error?e.message:"平台不可用")}};useEffect(()=>{void refresh()},[]);useEffect(()=>{if(active)call<Knowledge[]>(`/api/websites/${active.id}/knowledge`).then(setDocs).catch(e=>setNotice(e.message));else setDocs([])},[siteId,sites.length]);
 const ensureWorkspaceProject=async(site:Site):Promise<Site>=>{if(site.workspace_project_id)return site;const response=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:site.domain,country_code:site.country_code||"US",language_code:site.language_code||"en"})});const project=await response.json();if(!response.ok||!project.id)throw new Error(project.error||"无法创建站点项目");const updated=await call<Site>(`/api/websites/${site.id}`,{method:"PATCH",body:JSON.stringify({workspace_project_id:project.id})});setSites(current=>current.map(item=>item.id===updated.id?updated:item));return updated};
 const create=async()=>{try{const response=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.domain,country_code:"US",language_code:"en"})});const project=await response.json();if(!response.ok||!project.id)throw new Error(project.error||"无法创建站点项目");const s=await call<Site>("/api/websites",{method:"POST",body:JSON.stringify({...form,workspace_project_id:project.id})});await refresh();nav(`/agent-platform/site/${s.id}`)}catch(e){setNotice(e instanceof Error?e.message:"新建失败")}};
 const remove=async(s:Site)=>{if(!window.confirm(`确认删除网站「${s.domain}」吗？\n会删除知识库和新版资料；旧关键词、标题、正文项目不会自动删除。`))return;await call(`/api/websites/${s.id}`,{method:"DELETE"});await refresh();if(s.id===Number(siteId))nav("/agent-platform")};
 const addDoc=async()=>{if(!active)return;await call(`/api/websites/${active.id}/knowledge`,{method:"POST",body:JSON.stringify({title:doc.title,source_type:"upload",content:doc.content})});setDoc({title:"",content:""});setDocs(await call(`/api/websites/${active.id}/knowledge`))}; const upload=(f:File|undefined)=>{if(!f)return;const r=new FileReader();r.onload=()=>setDoc({title:f.name,content:String(r.result||"")});r.readAsText(f)};const link=(path:string)=>active?.workspace_project_id?`${path}?project_id=${active.workspace_project_id}&site_id=${active.id}`:"#";const openModule=async(event:React.MouseEvent<HTMLAnchorElement>,path:string)=>{if(!active)return;event.preventDefault();try{const ready=await ensureWorkspaceProject(active);nav(`${path}?project_id=${ready.workspace_project_id}&site_id=${ready.id}`)}catch(error){setNotice(error instanceof Error?error.message:"项目跳转失败")}};
 return <section className="simple-console"><header className="simple-hero"><p>多站点 SEO 工作台</p><h2>{active?active.domain:"选择一个网站开始"}</h2><span>{notice}</span></header><nav className="site-tabs">{sites.map(s=><div key={s.id} className={`site-tab ${s.id===Number(siteId)?"active":""}`}><button onClick={()=>nav(`/agent-platform/site/${s.id}`)}>{s.domain}</button><button className="remove-site" title="删除网站" onClick={()=>void remove(s)}>×</button></div>)}<button className="new" onClick={()=>nav("/agent-platform")}>+ 新建网站</button></nav>{!active?<section className="simple-panel new-site"><h3>新建独立网站</h3><input placeholder="域名，例如 example.com" value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}/><input placeholder="行业，例如 Industrial LED" value={form.industry} onChange={e=>setForm({...form,industry:e.target.value})}/><button disabled={!form.domain||!form.industry} onClick={()=>void create()}>创建网站控制台</button></section>:<><section className="site-dashboard"><a className="module-card" href={link("/research")} onClick={event=>void openModule(event,"/research")}><small>01 · 第一步</small><h3>挖掘关键词</h3><p>为当前网站发现、审核并入库关键词。</p><b>开始挖掘 →</b></a><a className="module-card" href={link("/titles")} onClick={event=>void openModule(event,"/titles")}><small>02 · 第二步</small><h3>关键词生成标题</h3><p>用当前网站的关键词生成并选择 SEO 标题。</p><b>生成标题 →</b></a><a className="module-card" href={link("/content")} onClick={event=>void openModule(event,"/content")}><small>03 · 第三步</small><h3>标题生成内容</h3><p>写作时自动读取本网站知识库资料。</p><b>生成内容 →</b></a><a className="module-card" href="#knowledge"><small>04 · 资料中心</small><h3>公司知识库</h3><p>{docs.length} 份已收录资料，可持续补充。</p><b>管理知识库 ↓</b></a></section><section className="simple-panel knowledge" id="knowledge"><h3>公司知识库</h3><p>上传公司介绍、产品参数、案例、FAQ 或资料文档；这些内容会随当前网站进入写作资料包。</p><input placeholder="资料标题" value={doc.title} onChange={e=>setDoc({...doc,title:e.target.value})}/><textarea placeholder="粘贴资料内容…" value={doc.content} onChange={e=>setDoc({...doc,content:e.target.value})}/><label>上传文本资料 <input type="file" accept=".txt,.md,.html,.csv" onChange={e=>upload(e.target.files?.[0])}/></label><button disabled={!doc.title||!doc.content} onClick={()=>void addDoc()}>加入知识库</button><h4>已收录资料（{docs.length}）</h4>{docs.map(d=><article key={d.id}><b>{d.title}</b><span>{d.source_type} · {d.status}</span></article>)}</section></>}</section>}
